# This file controls the AWS CodeBuild

version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn package
#    - mvn clean prepare-package war:exploded
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - mv target/aws-elastic-beanstalk-example-2-0.0.1-SNAPSHOT.war aws-elastic-beanstalk-example-2-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - aws-elastic-beanstalk-example-2-0.0.1-SNAPSHOT.war